# Generated by Django 5.2 on 2025-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
