# Generated by Django 5.2 on 2025-05-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_customer_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='locations',
            new_name='location',
        ),
    ]
